sudo: required
services:
  - postgresql
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install pep8
addons:
  - postgresql: "9.4"
script:
  - ./scripts/cibuild.sh
