site_name: NetBox

pages:
    - 'Introduction': 'index.md'
    - 'Installation':
        - 'PostgreSQL': 'installation/postgresql.md'
        - 'NetBox': 'installation/netbox.md'
        - 'Web Server': 'installation/web-server.md'
        - 'Upgrading': 'installation/upgrading.md'
        - 'Alternate Install: Docker': 'installation/docker.md'
    - 'Configuration': 'configuration.md'
    - 'Data Model':
        - 'Circuits': 'data-model/circuits.md'
        - 'DCIM': 'data-model/dcim.md'
        - 'IPAM': 'data-model/ipam.md'
        - 'Secrets': 'data-model/secrets.md'
        - 'Extras': 'data-model/extras.md'
    - 'API Integration': 'api-integration.md'

markdown_extensions:
    - admonition:
