# Generated by Django 4.2.16 on 2024-12-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('site_tag', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('tags', models.JSONField()),
                ('num_devices', models.PositiveIntegerField()),
                ('num_vlans', models.PositiveIntegerField()),
                ('vlan_requirement', models.JSONField()),
                ('num_prefixes', models.PositiveIntegerField()),
                ('num_racks', models.PositiveIntegerField()),
                ('devices_per_rack', models.PositiveIntegerField()),
                ('vrf_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
