# Generated by Django 4.2.16 on 2024-12-24 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0116_fix_dynamic_group_group_type_data_migration'),
        ('naas', '0003_alter_siteonboarding_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteonboarding',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siteonboarding',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='siteonboardings', to='extras.tag'),
        ),
    ]
