# Generated by Django 4.2.16 on 2024-12-24 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0116_fix_dynamic_group_group_type_data_migration'),
        ('naas', '0004_alter_siteonboarding_id_alter_siteonboarding_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOnboardingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteonboarding_tags', to='naas.siteonboarding')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteonboarding_tags', to='extras.tag')),
            ],
            options={
                'unique_together': {('site_onboarding', 'tag')},
            },
        ),
    ]
