# Generated by Django 4.2.16 on 2024-12-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0005_tag_siteonboardingtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteonboarding',
            options={'verbose_name': 'Site Onboarding', 'verbose_name_plural': 'Site Onboardings'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.DeleteModel(
            name='SiteOnboardingTag',
        ),
    ]
