# Generated by Django 4.2.16 on 2024-12-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0006_alter_siteonboarding_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOnboardingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('site_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteonboarding_tags', to='naas.siteonboarding')),
            ],
        ),
    ]
