# Generated by Django 4.2.16 on 2025-01-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('ipam', '0050_vlangroup_range'),
        ('naas', '0007_siteonboardingtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='devices_per_rack',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='num_racks',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='vrf_name',
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='prefix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='site_onboardings', to='ipam.prefix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='racks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='site_onboardings', to='dcim.rack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='uplink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='vlan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='site_onboardings', to='ipam.vlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='vlan_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='vrf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='site_onboardings', to='ipam.vrf'),
            preserve_default=False,
        ),
    ]
