# Generated by Django 4.2.16 on 2025-01-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0050_vlangroup_range'),
        ('dcim', '0062_module_data_migration'),
        ('naas', '0008_delete_tag_remove_siteonboarding_devices_per_rack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.devicetype')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.rack')),
            ],
        ),
        migrations.AlterModelOptions(
            name='siteonboarding',
            options={},
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='device_number',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='racks',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='site_tag',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='vlan',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='vlan_description',
        ),
        migrations.RemoveField(
            model_name='siteonboarding',
            name='vrf',
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='vlan_requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='vlans',
            field=models.ManyToManyField(blank=True, related_name='site_onboardings', to='ipam.vlan'),
        ),
        migrations.AlterField(
            model_name='siteonboarding',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='siteonboarding',
            name='uplink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SiteOnboardingTag',
        ),
        migrations.AddField(
            model_name='device',
            name='site_onboarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='naas.siteonboarding'),
        ),
        migrations.AddField(
            model_name='device',
            name='vrfs',
            field=models.ManyToManyField(blank=True, to='ipam.vrf'),
        ),
    ]
