# Generated by Django 4.2.16 on 2025-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0009_device_alter_siteonboarding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteonboarding',
            name='vlan_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteonboarding',
            name='vlan_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
